### ISSUE TITLE
Problem with AtomicAdd()

### ISSUE THREAD

**Issue by AhmadObeid** [hcho3/eigenmap_gpu#1]
Hello, and thank you for sharing.

I am facing a problem with the Makefile compilation. When I run Makefile in eigenmap_gpu directory, specifically when it reaches target book.o, I get an error telling me that the function atomicAdd is already defined as seen below. 

**_nvcc -arch=sm_35 -rdc=true -c book.cu -o book.o -Xcompiler -fPIC -I./matio/include 
book.cu(161): error: function "atomicAdd(double *, double)" has already been defined

1 error detected in the compilation of "/tmp/tmpxft_00002825_00000000-4_book.cpp4.ii".
Makefile:47: recipe for target 'book.o' failed
make: *** [book.o] Error 2_**

I looked around and apparently it may be a problem that has to do with the cuda version, but I am still uncertain of what to do. 

I am using Ubuntu 18.04, with nvidia-driver 390, and its compatible version of Cuda, which is 9.1. 
I also made sure that matio, Atlas and Magma are in their correct locations, and made sure that said locations are defined in the Makefile. 

Thank you for your help

**Comment by chyunsu3** [comment]
@AhmadObeid The code was written long time ago (year 2014) and back then `atomicAdd()` did not support adding double-precision numbers. You should remove the function.

**Comment by AhmadObeid** [comment]
Thank you for the answer. 
I did that. But won't that create any problems?

**Comment by chyunsu3** [comment]
No, since CUDA now has `atomicAdd()` implemented for double-precision types.
